#include <stdio.h>
#include <stdbool.h>
#include <Ecore.h>
#include <EWebKit_Extension.h>
#include <JavaScriptCore/JavaScript.h>

static double number_static_prop = 0.0;
static JSClassRef example_class_ref = NULL;

typedef struct _Example_Class_Data {
   Ecore_Timer *timer;
   JSContextRef ctx;
   JSValueRef timeout_cb;
   double tick;
   double number;
} Example_Class_Data;

static JSValueRef
get_number_static_prop(JSContextRef ctx,
                       JSObjectRef obj,
                       JSStringRef propertyName,
                       JSValueRef *exception)
{
   return JSValueMakeNumber(ctx, number_static_prop);
}

static bool
set_number_static_prop(JSContextRef ctx,
                       JSObjectRef obj,
                       JSStringRef propertyName,
                       JSValueRef value,
                       JSValueRef *exception)
{
   double d = JSValueToNumber(ctx, value, exception);

   if (*exception)
     {
        fprintf(stderr, "Could not get the string value\n");
        return false;
     }
   number_static_prop = d;
   return true;
}

static JSValueRef
sum_array(JSContextRef ctx,
          JSObjectRef function,
          JSObjectRef obj,
          size_t argc,
          const JSValueRef argv[],
          JSValueRef* exception)
{
   size_t len, i;
   JSObjectRef array;
   JSValueRef len_prop;
   JSStringRef prop_name;
   double sum = 0.0;

   if (!argc)
     {
        fprintf(stderr, "No arguments\n");
        return NULL;
     }

   if (!JSValueIsArray(ctx, argv[0]))
     {
        fprintf(stderr, "The argument must be an array of numbers\n");
        return NULL;
     }

   array = JSValueToObject(ctx, argv[0], exception);

   if (!array)
     {
        fprintf(stderr, "Could not Convert The array to object\n");
        return NULL;
     }

   prop_name = JSStringCreateWithUTF8CString("length");
   len_prop = JSObjectGetProperty(ctx, array, prop_name, exception);
   JSStringRelease(prop_name);

   if (JSValueIsUndefined(ctx, len_prop))
     {
        fprintf(stderr, "Could not retrive the array's len\n");
        return NULL;
     }

   len = (size_t)JSValueToNumber(ctx, len_prop, NULL);

   for (i = 0; i < len; i++)
     {
        JSValueRef value = JSObjectGetPropertyAtIndex(ctx, array, i, exception);
        if (!JSValueIsNumber(ctx, value))
          {
             fprintf(stderr,
                     "The element at index '%zu' is not a number!\n", i);
             return NULL;
          }
        sum += JSValueToNumber(ctx, value , NULL);
     }

   return JSValueMakeNumber(ctx, sum);
}

static JSValueRef
convertToType(JSContextRef ctx,
              JSObjectRef obj,
              JSType type,
              JSValueRef* exception)
{
   switch (type)
     {
      case kJSTypeString:
        {
           Example_Class_Data *priv_data = JSObjectGetPrivate(obj);
           char buf[32];
           snprintf(buf, sizeof(buf), "Example Class {priv data: %g}",
                    priv_data->number);
           JSStringRef string = JSStringCreateWithUTF8CString(buf);
           JSValueRef result = JSValueMakeString(ctx, string);
           JSStringRelease(string);
           return result;
        }
      default:
         return JSValueMakeNull(ctx);
     }
}

static JSValueRef
example_function_cb(JSContextRef ctx,
                    JSObjectRef function,
                    JSObjectRef obj,
                    size_t argc,
                    const JSValueRef argv[],
                    JSValueRef* exception)
{
   JSValueRef value;
   JSStringRef str = JSStringCreateWithUTF8CString("This is a string generated by the exampleFunction()");
   value = JSValueMakeString(ctx, str);
   JSStringRelease(str);
   return value;
}

static Eina_Bool
_timeout(void *data)
{
   JSValueRef arg;
   JSObjectRef obj = data;
   Example_Class_Data *priv_data = JSObjectGetPrivate(obj);
   JSObjectRef function = JSValueToObject(priv_data->ctx,
                                          priv_data->timeout_cb, NULL);
   arg = JSValueMakeNumber(priv_data->ctx, priv_data->tick);
   JSObjectCallAsFunction(priv_data->ctx, function, obj, 1,
                          &arg, NULL);
   priv_data->tick++;
   return ECORE_CALLBACK_RENEW;
}

static JSValueRef
register_timer_cb(JSContextRef ctx,
                  JSObjectRef function,
                  JSObjectRef obj,
                  size_t argc,
                  const JSValueRef argv[],
                  JSValueRef *exception)
{
   double timeout_time;
   Example_Class_Data *priv_data = JSObjectGetPrivate(obj);

   if (priv_data->timer)
     {
        fprintf(stderr, "Timer already registered\n");
        return JSValueMakeBoolean(ctx, false);
     }

   if (argc < 2)
     {
        fprintf(stderr, "Missing arguments\n");
        return JSValueMakeBoolean(ctx, false);
     }

   timeout_time = JSValueToNumber(ctx, argv[0], NULL);

   priv_data->timer = ecore_timer_add(timeout_time, _timeout, obj);

   if (!priv_data->timer)
     {
        fprintf(stderr, "Could not create the timer\n");
        return JSValueMakeBoolean(ctx, false);
     }

   priv_data->timeout_cb = argv[1];
   //Do not garbage collect
   priv_data->tick = 0;
   JSValueProtect(ctx, priv_data->timeout_cb);
   return JSValueMakeBoolean(ctx, true);
}

static JSValueRef
unregister_timer_cb(JSContextRef ctx,
                    JSObjectRef function,
                    JSObjectRef obj,
                    size_t argc,
                    const JSValueRef argv[],
                    JSValueRef* exception)
{
   Example_Class_Data *priv_data = JSObjectGetPrivate(obj);

   if (priv_data->timer)
     {
        ecore_timer_del(priv_data->timer);
        priv_data->timer = NULL;
        JSValueUnprotect(ctx, priv_data->timeout_cb);
        priv_data->timeout_cb = NULL;
        return JSValueMakeBoolean(ctx, true);
     }
   return JSValueMakeBoolean(ctx, false);
}

static void
register_function(JSContextRef ctx,
                  JSObjectRef obj,
                  const char *name,
                  JSObjectCallAsFunctionCallback cb)
{
   JSStringRef func_name = JSStringCreateWithUTF8CString(name);
   JSObjectSetProperty(ctx, obj, func_name,
                       JSObjectMakeFunctionWithCallback(ctx, func_name, cb),
                       kJSPropertyAttributeNone, NULL);
   JSStringRelease(func_name);
}

static JSObjectRef
constructor(JSContextRef ctx,
            JSObjectRef constructor,
            size_t argc,
            const JSValueRef argv[],
            JSValueRef *exception)
{
   JSObjectRef obj;
   obj = JSObjectMake(ctx, example_class_ref, NULL);
   register_function(ctx, obj, "exampleFunction", example_function_cb);
   register_function(ctx, obj, "registerTimer", register_timer_cb);
   register_function(ctx, obj, "unregisterTimer", unregister_timer_cb);
   return obj;
}

static JSValueRef
get_property(JSContextRef ctx,
             JSObjectRef obj,
             JSStringRef prop_name,
             JSValueRef *exception)
{
   if (!JSStringIsEqualToUTF8CString(prop_name, "instanceProperty"))
     return NULL; //try the static properties
   Example_Class_Data *priv_data = JSObjectGetPrivate(obj);
   return JSValueMakeNumber(ctx, priv_data->number);
}

static bool
set_property(JSContextRef ctx,
             JSObjectRef obj,
             JSStringRef prop_name,
             JSValueRef value,
             JSValueRef *exception)
{
   Example_Class_Data *priv_data;
   double d;

   if (!JSStringIsEqualToUTF8CString(prop_name, "instanceProperty"))
     return false; //try the static properties

   d = JSValueToNumber(ctx, value, exception);
   if (*exception)
     {
        fprintf(stderr, "Could not set the instanceProperty\n");
        return true;
     }
   priv_data = JSObjectGetPrivate(obj);
   priv_data->number = d;
   return true;
}

static void
initialize(JSContextRef ctx, JSObjectRef obj)
{
   Example_Class_Data *priv_data = calloc(1, sizeof(Example_Class_Data));
   priv_data->ctx = JSContextGetGlobalContext(ctx);
   JSObjectSetPrivate(obj, priv_data);
}

static void
finalize(JSObjectRef obj)
{
   Example_Class_Data *priv_data = JSObjectGetPrivate(obj);
   if (!priv_data)
     return;
   ecore_timer_del(priv_data->timer);
   free(priv_data);
}

static const JSStaticValue static_properties[] = {
    { "NumberStaticProperty", get_number_static_prop, set_number_static_prop,
      kJSPropertyAttributeDontDelete },
    { 0, 0, 0, 0 }
};

static const JSStaticFunction static_functions[] = {
  { "SumArrayStaticFunction", sum_array,
    kJSPropertyAttributeReadOnly | kJSPropertyAttributeDontDelete },
  { 0, 0, 0 }
};

static const JSClassDefinition example_class = {
  0,                      // version
  kJSClassAttributeNone,  // attributes
  "ExampleClass",         // className
  NULL,                   // parentClass
  static_properties,
  static_functions,
  initialize,
  finalize,
  NULL,                  //has property
  get_property,
  set_property,
  NULL,                  //deleteProperty
  NULL,                  //get property names
  NULL,
  constructor,
  NULL,                  //hasInstance
  convertToType
};

//Javasript is ready to load new classes/properties
static void
on_window_object_cleared(Ewk_Page *page, void *data)
{
   JSObjectRef js_global_obj, js_class_obj;
   JSGlobalContextRef js_context;
   JSStringRef str;

   js_context = ewk_page_js_global_context_get(page);
   EINA_SAFETY_ON_NULL_RETURN(js_context);

   js_global_obj = JSContextGetGlobalObject(js_context);
   example_class_ref = JSClassCreate(&example_class);
   js_class_obj = JSObjectMake(js_context, example_class_ref, NULL);
   str = JSStringCreateWithUTF8CString("ExampleClass");
   JSObjectSetProperty(js_context, js_global_obj, str, js_class_obj,
                       kJSPropertyAttributeNone, NULL);
   JSStringRelease(str);
}

static const struct EwkPageClient extension_page = {
  .version = 1,
  .data = NULL,
  .load_started = NULL,
  .load_finished = NULL,
  .window_object_cleared = on_window_object_cleared
};

static void
on_page_add(Ewk_Page *page, void *data)
{
   ewk_page_client_register(page, &extension_page);
}

static void
on_page_del(Ewk_Page *page, void *data)
{
   ewk_page_client_unregister(page, &extension_page);
}

static struct EwkExtensionClient client_extension = {
  .version = 1,
  .data = NULL,
  .page_add = on_page_add,
  .page_del = on_page_del,
  .message_received = NULL
};

//Automatically called by WebKit
void
ewk_extension_init(Ewk_Extension *extension)
{
   if (!ewk_extension_client_add(extension, &client_extension))
     fprintf(stderr, "Could not add the extension!\n");
}
